### PR TITLE
Add CC BY-SA 4.0 license to make site open source

### PR DESCRIPTION
**Pull request by vendion**
I can't believe that the site went this long before anyone noticed that this site wasn't licensed, and all contributions was to a proprietary site. To correct this we should have a Free/Open license to help encourage future contributions.  The [Creative Commons Attribution-ShareAlike license](https://creativecommons.org/licenses/by-sa/4.0/) is a copyleft license that is recognized by the FSF as a Free license (similar to the GNU {GPL,LGPL,AGPL,Free Documentation License} but without all the viral nature and weirdness of GNU licenses).

If there are any issues with the CC BY-SA license another one can be used instead, it's just this license is better for this type of project than a software based one (e.g. GNU {GPL,LGPL,AGPL}, BSD, Apache, MIT, etc).

### CODE REVIEW

**Comment by seabre** [comment]
IMHO this is fine, but the caveat is this: if this is done, only contributions from here on out can be considered under this license. In order to cover the whole project under this license, permission would have to be granted by every single committer in writing that their contributions are now granted under the new license.

**Comment by StrangeWill** [comment]
Few things:

> If there are any issues with the CC BY-SA license another one can be used instead, it's just this license is better for this type of project than a software based one (e.g. GNU {GPL,LGPL,AGPL}, BSD, Apache, MIT, etc).

I'm curious, how does this fit better than MIT/MPL? CC's own FAQ doesn't like it being applied to code: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Being _mostly_ markup puts us in this weird "ehh it's mostly _technically_ documentation", but still.

---

Also: considering we're _effectively_ re-licensing this project and we don't require a CLA, where does this stand legally? Don't we need approval from all contributors?



However dang... good catch!

**Comment by vendion** [comment]
Yes I am aware of that Caveat, one way to go about that is we have a _CONTRIBUTORS_ file that will act as a sort of waver that past contributors can "sign" be adding their name and GitHub username to that says that they agree with their previous contributions be under this new license.

Moving forward "signing" off like that will then be optional. If someone doesn't want to sign the _CONTRIBUTORS_ "agreement" then we can remove their contributions if desired.

**Comment by StrangeWill** [comment]
Either way though, I'll sign off on the Windows support I added with whatever open license is decided going forward, my questions were mostly out of curiosity.

**Comment by vendion** [comment]
@StrangeWill MIT/MPL is more geared towards technical projects which this kind of fits but in a odd way. Plus I don't know if it's still there but at one point the MPL had a weird clause in it that require all litigation to happen in Santa Monica, CA (IIRC).  Other than that weird clause I'm open to other licenses, just IMO the CC BY-SA fits a bit better.

**Comment by dereklucas** [comment]
Why don't you make a PR to start that? I think that was forgotten because we need to discuss what is the right thing to do for all the contributors who only PR'd their info into the devs page. But it'd be good to get it for the few code contributors.

**Comment by StrangeWill** [comment]
_Totally_ can, just was confirming that was the idea (just something as simple as this: https://github.com/calagator/calagator/blob/master/CONTRIBUTORS.md or something more?) and I wasn't off course on that thought. I've never retroactively signed my code over from unlicensed to licensed so just wanted to defer to @vendion's opinion being as they seemed to have a much clearer idea/plan than I did.

**Comment by dereklucas** [comment]
I think that `CONTRIBUTORS.md` seems perfect unless @vendion says otherwise.

**Comment by vendion** [comment]
This PR got accidentally merged before that could be added. I do agree with @dereklucas anyone should feel free to make a PR that adds the _CONTRBUTORS_ file and get one PR closer to their 5 for [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

Working wise the file probably needs to start with verbiage similar to the following:

> This is the official list of people who can contribute
> (and typically have contributed) code to the 
> chadev.github.io repo.
> 
> Names should be added to this file only after verifying that
> the individual or the individual's organization has agreed to
> the CC BY-SA 4.0 International found in the
> COPYING file
> 
> Names should be added to this file like so:
>     Individual's name <submission email address>
>     Individual's name <submission email address> <email2> <emailN>
> 
> Please keep the list sorted.

I adapted that from another repo so it probably could be worded a bit better but should work for our needs.

**Comment by StrangeWill** [comment]
Sweet, I'll update my PR to include that. Thanks!

**Pull request merged**
