### PR TITLE
New slack signup page.

### PR DESCRIPTION
**Pull request by StrangeWill**
Slack has a signup page now available at https://chadev.slack.com/signup that we should be able to enable.

Do we want to do this? If so change the settings on Slack, test the Slack end and accept the PR, otherwise reject.

### CODE REVIEW

**Comment by StrangeWill** [comment]
Thanks to agarzola for pointing out this new functionality

**Comment by acedrew** [comment]
@StrangeWill @agarzola from my understanding this has always (since I've been on slack) been a feature, however you have to specify email domains that are allowed to sign up. I don't think this is a viable solution, but I'll leave this open for a while in case someone wants to weigh in and clear up any of my misunderstanding

**Comment by StrangeWill** [comment]
@acedrew Can you enable it and have me attempt to sign up from like Gmail?

**Comment by acedrew** [comment]
My only option to enable that I see is to fill in a list of domains

**Comment by StrangeWill** [comment]
@acedrew Boo, I thought they changed that... oh well, feel free to reject this.

**Comment by acedrew** [comment]
Closing until slack adds relevant functionality...

**Pull request closed without merging**
