### PR TITLE
Richard Smith (ChaDev+DevOps) add to Devs list

### PR DESCRIPTION
**Pull request by rls2org**

### CODE REVIEW

**Comment by kylegordy** [comment]
@rls2org I just checked out your commit and your twitter URL is broken for some reason… Any ideas? Other than that everything looked great!

**Comment by rls2org** [comment]
Just a stupid misspelling. I fixed it and committed. This is my first pull
request go around... do I need to submit another pull request?

**Comment by seabre** [comment]
:+1: merging

**Comment by seabre** [comment]
@rls2org Nah. If you have an existing pull request and you need to fix something, make commit(s) to the same branch in your fork that your pull request is pulling from.

**Pull request merged**
