### PR TITLE
adding cavewoman info

### PR DESCRIPTION
**Pull request by cavewoman**

### CODE REVIEW

**Comment by keathley** [comment]
Do we need the quotes around the gravatar id?  I can't remember if that breaks things or not.

**Comment by C0deMaver1ck** [comment]
:shipit:

**Comment by C0deMaver1ck** [comment]
My entry has quotes, and other's don't. It seems it works fine.

**Comment by vendion** [comment]
I think the quotes gets parsed out, typically out convention has been to no use quotes around the Gravatar ID.  Otherwise this looks good to me and I don't see why it shouldn't get merged in.

**Pull request merged**
