### PR TITLE
Create e1337kat.md

### PR DESCRIPTION
**Pull request by E1337Kat**

### CODE REVIEW

**Comment by vendion** [comment]
I don't know if the linked website is appropriate in this case. There is nothing there to verify that it's your site, there also seems to be nothing there other than a joke about emoji.

If you don't have a personal website, or don't want it listed then leaving the website out is preferred.

**Comment by E1337Kat** [comment]
That is my website lol. it's a github pages. I can modify the page to be more descriptive and specify that I am the owner.

**Comment by E1337Kat** [comment]
I have edited the site to make it a little more purposeful: https://xn--gi8hwa63hj6b.ws/

**Comment by vendion** [comment]
That works, thanks for your understanding :+1:

**Comment by E1337Kat** [comment]
No problem, sorry for being an idiot with my site.

**Pull request merged**
