### PR TITLE
My last commit introduced a bug on mobile that this commit fixes.

### PR DESCRIPTION
**Pull request by brettwise**

### CODE REVIEW

**Comment by keathley** [comment]
Can you post some screenshots of the different browsers just to make sure that they are all working still.  I should have had you do that on the last PR.

**Comment by brettwise** [comment]
Silly me.

https://www.browserstack.com/screenshots/aa69dd183bcb249acba132e4adbe42d974b4d657

**Comment by StrangeWill** [comment]
Obviously we need a stringent QA process with sign-off now.

**Comment by StrangeWill** [comment]
On a serious note -- free for open source... can we get our hands on that?

**Comment by brettwise** [comment]
I just sent them a message about getting access for us. Will see what they say.

**Comment by keathley** [comment]
Thanks for the screens.  Looks fixed to me :tada:

**Comment by brettwise** [comment]
Yo @StrangeWill have access to the full browser suite now for Chadev. Can add you to org with an email.

**Comment by kylegordy** [comment]
@brettwise Can you make sure I get added too please :) I'm kyletgordy@gmail.com.

**Comment by brettwise** [comment]
For sure.

**Pull request merged**
